catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("books/", views.BookListView.as_view(), name="books"),
    path("book/<int:pk>", views.BookDetailView.as_view(), name="book-detail"),
    path("authors/", views.AuthorListView.as_view(), name="authors"),
    path("author/<int:pk>", views.AuthorDetailView.as_view(), name="author-detail"),
]

locallibray/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
    path("", RedirectView.as_view(url="/catalog/", permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from pyexpat import model
from django.db import models
from django.urls import reverse
import uuid

# Create your models here.
class Genre(models.Model):
    """Model representing a book genre (e.g. Science Fiction, Non Fiction)."""

    name = models.CharField(
        max_length=200, help_text="Enter a book genre (e.g. Science Fiction)"
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""

    name = models.CharField(
        max_length=200,
        help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)",
    )

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)

    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book"
    )
    isbn = models.CharField(
        "ISBN",
        max_length=13,
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
    )

    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    language = models.ForeignKey("Language", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse("book-detail", args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ", ".join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = "Genre"


class BookInstance(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="Unique ID for this particular book across whole library",
    )
    book = models.ForeignKey("Book", on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ("m", "Maintenance"),
        ("o", "On loan"),
        ("a", "Available"),
        ("r", "Reserved"),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default="m",
        help_text="Book availability",
    )

    class Meta:
        ordering = ["due_back"]

    def __str__(self):
        """String for representing the Model object."""
        return f"{self.id} ({self.book.title})"


class Author(models.Model):
    """Model representing an author."""

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField("Died", null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse("author-detail", args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f"{self.last_name}, {self.first_name}"

catalog/views.py
from pyexpat import model
from django.shortcuts import render, HttpResponse
from catalog.models import Book, BookInstance, Author, Genre, Language
from django.views import generic

# Create your views here.
def index(request):

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact="a").count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    # visiter

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_books": num_books,
        "num_instances": num_instances,
        "num_instances_available": num_instances_available,
        "num_authors": num_authors,
        "num_visits": num_visits,
    }
    return render(request, "index.html", context=context)


class BookListView(generic.ListView):
    """Generic class-based view for a list of books."""

    model = Book
    paginate_by = 2


class BookDetailView(generic.DetailView):
    """Generic class-based detail view for a book."""

    model = Book


class AuthorListView(generic.ListView):
    """Generic class-based detail view for a book."""

    model = Author
    paginate_by = 2


class AuthorDetailView(generic.DetailView):
    """Generic class-based detail view for a book."""

    model = Author

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}{% endblock title %} | MDN test
        </title>
    {% block head %}
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock head %}
</head>
<body>
    
    <div class="wrap con row">
        <div class="side_bar_box cell">
        {% block side_bar %}
                <ul>
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'books' %}"> All book </a></li>
                    <li><a href="{% url 'authors' %}">All authors</a></li>
                </ul>
        {% endblock side_bar %}
        </div>

        <div class="content_box cell">
        {% block content %}
        {% endblock content %}
        {% block pagination %}
        {% if is_paginated %}
            <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                <p>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</p>
                </span>
                {% if page_obj.has_next %}
                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
            </div>
        {% endif %}
        {% endblock %} 
    </div>
    </div>
</body>
</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block title %}
author detail
{% endblock title %}

{% block content %}

    <h1>Author Name : {{author}}</h1>
    <h2>date_of_birth : {{author.date_of_birth}}</h2>
    <h2>date_of_death : {{author.date_of_death}}</h2>


    {% for book in author.book_set.all  %}
    <p>{{book}}</p>
    {% endfor %}



{% endblock content %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block title %}
author list
{% endblock title %}

{% block content %}

    <h1>author list</h1>
    <ul>

    {% for author in author_list %}
    <li>
        
        <a href="{{ author.get_absolute_url }}">{{ author }} details</a>
        
    </li>
    {% endfor %}

    </ul>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block title %}
Book detail
{% endblock title %}

{% block content %}
  <h1>Title: {{ author.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p>{{ copy.get_status_display }}</p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{copy.imprint}}</p>
      <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block title %}
Book List
{% endblock title %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}       
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}
home
{% endblock title %}

{% block content %}
<h1>Wellcome home</h1>

<h2>visitis {{num_visits}}</h2>

<p>let's make something by Django Python!!!</p>
<br>
<h2>변하는 컨텐츠들</h2>
<ul>
    <li>your book number :{{num_books}}</li>
    <li>your instances number : {{num_instances}}</li>
    <li>your instances_available number : {{num_instances_available}}</li>
    <li>your authors number : {{num_authors}}</li>
</ul>

{% endblock content %}